# Generated by Django 5.0.6 on 2024-06-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Car Models',
            },
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Drive Types',
            },
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Engine Types',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='acceleration',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='automatic_gearbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='car_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='engine_size',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='max_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='car_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.carmodel'),
        ),
        migrations.AddField(
            model_name='item',
            name='drive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.drivetype'),
        ),
        migrations.AddField(
            model_name='item',
            name='engine_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.enginetype'),
        ),
    ]
