# Generated by Django 5.0.6 on 2024-06-03 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_brand_carmodel_drivetype_enginetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='item.brand'),
        ),
    ]
