# Generated by Django 5.0.6 on 2024-06-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_itemprice_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
    ]
