# Generated by Django 5.0.6 on 2024-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_remove_item_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deposit',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='distance_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='price_per_addicional_distance',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
