# Generated by Django 5.0.6 on 2024-06-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_item_deposit_item_distance_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delivery_to_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_addicional_distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
