# Generated by Django 5.0.6 on 2024-06-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_item_deposit_alter_item_location_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_mail',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_phonenumber',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_surname',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
