# Generated by Django 5.0.6 on 2024-06-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_reservation_customer_mail_reservation_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_city',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
