# Generated by Django 5.0.6 on 2024-06-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_reservation_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='details_from_customer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
