# Generated by Django 5.0.6 on 2024-06-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_remove_reservation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
