# Generated by Django 5.0.6 on 2024-06-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_item_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='car_model',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
