# Generated by Django 5.0.4 on 2024-06-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_alter_item_car_model_delete_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
