# Generated by Django 5.0.4 on 2024-06-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_item_created_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='company_city',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='company_mail',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='company_phonenumber',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='company_visible_mail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='company_website',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
