# Generated by Django 5.0.4 on 2024-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_remove_reservation_item_reservation_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
