# Generated by Django 5.0.4 on 2024-06-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0026_reservation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_by',
        ),
    ]
