# Generated by Django 5.0.4 on 2024-06-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_remove_reservation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
